[package]
name = "gnvim"
version = "0.1.0"
authors = ["Ville Hakulinen <ville.hakulinen@gmail.com>"]

[profile.dev]
debug = true

[features]
unstable = []

[dependencies]

gio = "0.5"
cairo-rs = "0.5"
pango = "0.5"
pangocairo = "0.6"
glib = "0.6"
gdk = "0.9"

[dependencies.gtk]
version = "0.5"
features = ["v3_18"]

[dependencies.neovim-lib]
#version = "0.5"
#git = "https://github.com/daa84/neovim-lib"
git = "https://github.com/vhakulinen/neovim-lib"
branch = "newgrid-to-linegrid"
